import io
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

def convert_markdown_to_docx(topic: str, markdown_content: str) -> io.BytesIO:
    """
    Converts a Markdown research report into a styled Word (.docx) document stored in memory.
    """
    doc = Document()

    # Set document margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    # Document Header Title
    title = doc.add_heading(level=0)
    run = title.add_run(f"Research Report: {topic}")
    run.font.name = "Calibri"
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0, 51, 102) # Deep Blue Accent

    # Add subtitle metadata
    subtitle = doc.add_paragraph()
    sub_run = subtitle.add_run("Generated by Autonomous Multi-Agent AI Research Suite")
    sub_run.font.italic = True
    sub_run.font.size = Pt(10)
    sub_run.font.color.rgb = RGBColor(128, 128, 128)
    doc.add_paragraph().paragraph_format.space_after = Pt(12)

    # Process Markdown text lines
    lines = markdown_content.split('\n')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        # Headers
        if stripped.startswith('# '):
            h = doc.add_heading(level=1)
            r = h.add_run(stripped[2:])
            r.font.color.rgb = RGBColor(0, 51, 102)
        elif stripped.startswith('## '):
            h = doc.add_heading(level=2)
            r = h.add_run(stripped[3:])
            r.font.color.rgb = RGBColor(51, 102, 153)
        elif stripped.startswith('### '):
            h = doc.add_heading(level=3)
            r = h.add_run(stripped[4:])
            r.font.color.rgb = RGBColor(102, 102, 102)
        # Bullet list items
        elif stripped.startswith('- ') or stripped.startswith('* '):
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(stripped[2:])
        # Numbered list items
        elif len(stripped) > 2 and stripped[0].isdigit() and stripped[1] == '.':
            p = doc.add_paragraph(style='List Number')
            p.add_run(stripped[3:])
        # Regular Body Paragraphs
        else:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(6)
            p.add_run(stripped)

    # Save to memory buffer
    docx_buffer = io.BytesIO()
    doc.save(docx_buffer)
    docx_buffer.seek(0)
    return docx_buffer